---
- hosts: alertmanager
  gather_facts: true
  roles:
    - alertmanager

- hosts: node_exporter
  gather_facts: true
  roles:
    - prometheus_node_exporter

- hosts: prometheus
  gather_facts: true
  roles:
    - prometheus

- hosts: grafana
  gather_facts: true
  roles:
    - grafana